# Site settings
title: "Uma Sivakumar"
email: uma.sivakumar@yale.edu
url: https://umasivakumar14.github.io/
description: "Hi! I'm Uma Sivakumar, a CS major at Yale University. I am interested in creative use cases for Agentic AI, ML optimization, and game development. This is my personal website where I showcase my projects and skills."
keywords: "software engineer, web developer, software engineer intern, ML Intern, machine learning, game development, agentic AI, Yale University, CS major, computer science, web development, software development, programming, coding, projects, portfolio"
skills: "BSMS in Computer Science Yale'27 | Loves to explore ML, Web Dev, and Game Dev Tech"
meta_author: Sivakumar Uma

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6146d8 #18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 04023b #2c3e50 #FD6E8A
  secondary-dark: 04023b #233140 #A2122F

# Footer settings
# footer:
#   copyright: Dr. Henry Jekyll
#   location: Location
#   social: Around the Web
#   credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/uma-sivakumar-756793216/
  - title: github
    url: https://github.com/UMASIVAKUMAR14
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
